language: ruby
rvm:
- 2.1

branches:
  only:
  - gh-pages

install: 
  - gem install jekyll jekyll-paginate jemoji github-pages kramdown
  - bundle install
script: JEKYLL_ENV=production jekyll serve --baseurl "" --detach && htmlproof ./_site --disable-external --empty-alt-ignore

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

#gemfile: travisGemfile



notifications:
  email: false
